from __future__ import annotations

from typing import Any, Protocol

from ..models import CorpusType, RAGDocument


class ResponseWorkflowRepositoryPort(Protocol):
    """Aggregate-level storage boundary used by the response application services."""

    def get_response_event(self, event_id: str) -> Any: ...
    def list_response_events(self) -> list[Any]: ...
    def save_response_event(self, event: Any) -> None: ...
    def get_response_task(self, task_id: str) -> Any: ...
    def list_response_tasks(self, event_id: str) -> list[Any]: ...
    def save_response_task(self, task: Any) -> None: ...
    def get_event_risk_object(self, event_id: str, object_id: str) -> Any: ...
    def list_event_risk_objects(self, event_id: str) -> list[Any]: ...
    def save_event_risk_object(self, item: Any) -> None: ...
    def get_latest_evidence_package(self, package_id: str) -> Any: ...
    def list_evidence_packages(self, event_id: str, **kwargs: Any) -> list[Any]: ...
    def save_evidence_package(self, package: Any) -> None: ...
    def get_document_version(self, version_id: str) -> Any: ...
    def list_document_versions(self, document_id: str | None = None) -> list[Any]: ...
    def save_document_version_bundle(self, *args: Any, **kwargs: Any) -> None: ...
    def list_timeline_entries(self, event_id: str) -> list[Any]: ...
    def save_timeline_entry(self, entry: Any) -> None: ...
    def list_outbox_messages(self, **kwargs: Any) -> list[Any]: ...
    def save_outbox_message(self, message: Any) -> None: ...
    def create_database_backup(self, *args: Any, **kwargs: Any) -> Any: ...


class RagServicePort(Protocol):
    def query(
        self,
        corpus: CorpusType,
        query: str,
        filters: dict[str, str] | None = None,
        top_k: int = 3,
    ) -> list[RAGDocument]: ...

    def query_evidence_set(
        self,
        corpus: CorpusType,
        query: str,
        filters: dict[str, str] | None = None,
        top_k: int = 3,
        candidate_k: int = 20,
        token_budget: int | None = 1200,
        slots: list[str] | None = None,
        required_roles: list[str] | None = None,
    ) -> list[RAGDocument]: ...


class SimulationGatewayPort(Protocol):
    def dispatch(self, *args: Any, **kwargs: Any) -> Any: ...
